version: 2212.{build}
pull_requests:
  do_not_increment_build_number: true
skip_commits:
  message: /AppVeyor validate.*|Merge branch 'main' of.*|Update docs.*|Skip AppVeyor.*|Upload test results.*/
only_commits:
  files:
    - Evergreen/**/*
branches:
  only:
    - main
    - development
skip_tags: true
image: Visual Studio 2019
environment:
  GitHubKey:
    secure: bGxozoCJoYVeoQCF1W+tLhKbjvFoyr7zGcc2A57UiP356gpE7k8/fhqH6NPi8eQ2
  NuGetApiKey:
    secure: /YPozcX4yV1XCrZuS8DAhOmH/OOjkg6+zrCTT3lHR3a7/SY7S83JNNgYBsROlLq3
  Module: Evergreen
  Source: Evergreen
install:
- ps: . .\ci\Install.ps1
build_script:
- ps: . .\ci\GitHub.ps1
- ps: . .\ci\Build.ps1
test_script:
- ps: . .\ci\Tests.ps1
- ps: . .\ci\GitHub.ps1
deploy_script:
- ps: . .\ci\Deploy.ps1

