# Project information
site_name: Evergreen
site_url: https://stealthpuppy.com/evergreen
site_author: Aaron Parker
site_description: >-
  Enterprise automation for Windows applications and image management

# Repository
repo_name: aaronparker/evergreen
repo_url: https://github.com/aaronparker/evergreen
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 Aaron Parker

# Configuration
theme:
  name: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  #icon:
    #logo: logo
  logo: assets/images/evergreenbulb.png

# Table sort
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - assets/js/tables.js

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
  - social:
      cards: true
      cards_color:
        fill: "#009485"
        text: "#FFFFFF"
      cards_font: Roboto

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aaronparker
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/stealthpuppy
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/aaronedwardparker/
  generator: true

# Page tree
nav:
  - Home:
    - Introduction: index.md
    - Why Evergreen: why.md
    - How Evergreen works: how.md
    - Supported apps: apps.md
  - Getting started:
    - Installation: install.md
    - Find supported apps: find.md
    - Download installers: save.md
    - Test installer URLs: test.md
    - Export version information: export.md
    - Using Evergreen: use.md
    - Example usage: examples.md
    - Under the hood: under.md
    - How to use the Evergreen API: invoke.md
  - Evergreen Libraries:
    - Create a library: newlibrary.md
    - Update a library: updatelibrary.md
    - Retrieve details from a library: getlibrary.md
    - Install an application from a library: getlibraryapp.md
  - Resources:
    - Troubleshooting: troubleshoot.md
    - Known issues: issues.md
    - Changelog: changelog.md
  - Module help:
    - en-US:
      - about_Evergreen: help/en-US/about_Evergreen.md
      - Find-EvergreenApp: help/en-US/Find-EvergreenApp.md
      - Get-EvergreenApp: help/en-US/Get-EvergreenApp.md
      - Save-EvergreenApp: help/en-US/Save-EvergreenApp.md
      - Test-EvergreenApp: help/en-US/Test-EvergreenApp.md
      - New-EvergreenLibrary: help/en-US/New-EvergreenLibrary.md
      - Invoke-EvergreenLibraryUpdate: help/en-US/Invoke-EvergreenLibraryUpdate.md
      - Get-EvergreenLibrary: help/en-US/Get-EvergreenLibrary.md
      - Get-EvergreenLibraryApp: help/en-US/Get-EvergreenLibraryApp.md
      - Export-EvergreenApp: help/en-US/Export-EvergreenApp.md
      - Export-EvergreenManifest: help/en-US/Export-EvergreenManifest.md
  - App Tracker: https://stealthpuppy.com/apptracker/
  - PSPackageFactory: https://stealthpuppy.com/packagefactory/
